### ISSUE TITLE
[client] 지도에서 내 위치 버튼 버그 수정

### ISSUE THREAD

**Issue by po4tion** [toppingskorea/toppings-client#117]
- 모바일 한정 이슈 : 내 위치 버튼을 클릭한 후에 지도에서 움직이면 계속해서 내 위치로 이동된다.
- 내 위치 정보를 제공하지 않았을 경우 무한 로딩이 걸린다.

**Comment by ChanhyukPark-Tech** [comment]
thx!!!!
