### ISSUE TITLE
[개선] 마이페이지 이동시 하단 네비게이션이 깜빡입니다!

### ISSUE THREAD

**Issue by minsoo-web** [toppingskorea/toppings-client#141]
https://user-images.githubusercontent.com/57122180/217967635-e52f27f0-25b6-433e-9e41-2c72f68a4a96.mp4

**Comment by po4tion** [comment]
원인은 Suspense.CSROnly 네요... 해결 방법은 Suspense를 제거하거나 setnavigation을 Info 태그 외부에서 적용해야 할 것 같습니다.

**Comment by ChanhyukPark-Tech** [comment]
@minsoo-web thx! bro
