### ISSUE TITLE
[개선] 회원정보 수정시 특수문자 사용 가능

### ISSUE THREAD

**Issue by minsoo-web** [toppingskorea/toppings-client#144]
![image](https://user-images.githubusercontent.com/57122180/217968284-be3e0791-6cfb-45cd-a8af-88ea33995341.png)
![image](https://user-images.githubusercontent.com/57122180/217968318-4e24b65d-29f2-44da-b02a-27150631bc54.png)

**Comment by ChanhyukPark-Tech** [comment]
thx bro
