### ISSUE TITLE
[개선] map에서 내 위치를 보여주는 마커가 있었으면 좋겠습니다!

### ISSUE THREAD

**Issue by minsoo-web** [toppingskorea/toppings-client#157]
AS-IS
<img width="582" alt="image" src="https://user-images.githubusercontent.com/57122180/220008373-b6d4d096-6234-4e48-8adf-767ed4c256e2.png">

TO-BE
<img width="604" alt="image" src="https://user-images.githubusercontent.com/57122180/220008467-fa72e48b-9bf7-4b1e-8115-e713330ba78f.png">

**Comment by ChanhyukPark-Tech** [comment]
thx!!1
@po4tion 오네가이시마스
