### ISSUE TITLE
input, textarea클릭시 네비게이션 숨기기

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-client#37]
input, textarea클릭시 네비게이션 숨기기 
top, bottom navigation이 height를 너무 잡아먹으므로 focus되었을때 네비게이션을 숨깁시다 어떠신가요?

<img width="458" alt="image" src="https://user-images.githubusercontent.com/69495129/209083636-3b2d65a9-88a7-45d4-9c1d-c149476085fe.png">

**Comment by ChanhyukPark-Tech** [comment]
[fix: post/add에서 bottomnavigator 제거](https://github.com/toppingskorea/toppings-client/pull/40/commits/c396e10abc667ec04f9612e16a3aaf7df64770f7)

**Comment by po4tion** [comment]
@ChanhyukPark-Tech 
이거 사용안하는 페이지도 있어서 해당 컴포넌트 리팩토링이 필요할 것 같습니다.
