### ISSUE TITLE
AlertModal 최적화

### ISSUE THREAD

**Issue by po4tion** [toppingskorea/toppings-client#77]
현재 AlertModal의 rightClickFn과 rightText는 항상 같이 사용되고 있습니다. 이러한 경우 props를 두번 받는 것이 아닌 하나의 props로 제어하는 것이 사용자 입장에서 더욱 편하게 사용할 수 있다고 생각합니다.

**Comment by ChanhyukPark-Tech** [comment]
I fully agree with u
