### ISSUE TITLE
파일 export 문법 교체 사항 건의

### ISSUE THREAD

**Issue by po4tion** [toppingskorea/toppings-client#8]
코드 경로 : src/components/Skeleton

기존 찬혁님의 코드
<img width="297" alt="image" src="https://user-images.githubusercontent.com/55759551/200160274-e54779c5-fc51-4960-88db-f2992efb59d4.png">

변경한 코드
<img width="259" alt="image" src="https://user-images.githubusercontent.com/55759551/200160281-64b3379e-fb3b-4ca9-8041-ef1092aefc90.png">

찬혁님 처럼 하나의 변수에 여러 컴포넌트들을 넣어 밖으로 내보내게 될 경우 더욱 간결하게 처리할 수 있는 방법을 찾았습니다. 혹시 이 방법이 맘에 드신다면 향후 코드를 작성할 때 이런 식으로 작성해볼까 하는데 의견 부탁드립니다!

외부에서 사용하게 될 경우 찬혁님이 원하시던 방향인 Skleton.Box 처럼 사용 가능합니다!

**Comment by ChanhyukPark-Tech** [comment]
좋습니다 동규님이 해주신 방향 이 더 간결한것 같습니다.
import 구문에서는
어떻게 불러와야 `Skeleton.Box` 로 사용가능할까요?

**Comment by po4tion** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/55759551/200164543-b0aef93c-b63d-4356-a04c-d0435acc357f.png">

불러오는 것도 찬혁님이 처음 작성하였던 코드랑 똑같습니다!
